"""migrations

Revision ID: 090303ed39a5
Revises: 4f362dd006b4
Create Date: 2023-06-18 17:15:44.732985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "090303ed39a5"
down_revision = "4f362dd006b4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
