"""migrations

Revision ID: 0cca0828c813
Revises: 99918de266dd
Create Date: 2023-06-14 14:53:23.109679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cca0828c813'
down_revision = '99918de266dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('resident_id_fkey', 'resident', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('resident_id_fkey', 'resident', 'user', ['id'], ['id'])
    # ### end Alembic commands ###
