"""migrations

Revision ID: 166a9d327a82
Revises: 268e20a719f4
Create Date: 2023-06-14 15:30:38.272046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '166a9d327a82'
down_revision = '268e20a719f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visit', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visit', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
