"""migrations

Revision ID: 20277478b112
Revises: 6f561da2d260
Create Date: 2023-06-18 02:54:10.700634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20277478b112'
down_revision = '6f561da2d260'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
