"""migrations

Revision ID: 2b0eb70d4265
Revises: 20277478b112
Create Date: 2023-06-18 02:55:21.330602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b0eb70d4265'
down_revision = '20277478b112'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
