"""migrations

Revision ID: 4f362dd006b4
Revises: 2b0eb70d4265
Create Date: 2023-06-18 11:35:36.149698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f362dd006b4'
down_revision = '2b0eb70d4265'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
