"""migrations

Revision ID: 7c2f0a567e96
Revises: ccc6c9b5996d
Create Date: 2023-06-14 15:16:26.341274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c2f0a567e96'
down_revision = 'ccc6c9b5996d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
