"""migrations2

Revision ID: 7e3fdd9172c7
Revises: b2fbf5af2137
Create Date: 2023-06-14 01:38:34.909553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e3fdd9172c7'
down_revision = 'b2fbf5af2137'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resident', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'resident', 'user', ['user_id'], ['id'])
    op.add_column('visit', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visit', 'name')
    op.drop_constraint(None, 'resident', type_='foreignkey')
    op.drop_column('resident', 'user_id')
    # ### end Alembic commands ###
