"""migrations

Revision ID: 860c536f11c8
Revises: afd4a77b6778
Create Date: 2023-06-18 02:52:29.898724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '860c536f11c8'
down_revision = 'afd4a77b6778'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
