"""migrations

Revision ID: 9b2cadb7b34b
Revises: 50739560717a
Create Date: 2023-06-14 00:04:30.901231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b2cadb7b34b'
down_revision = '50739560717a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitor', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visitor', 'name')
    # ### end Alembic commands ###
