"""migrations

Revision ID: aa487e6c68c7
Revises: d488a3bca906
Create Date: 2023-06-14 02:46:48.681404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa487e6c68c7'
down_revision = 'd488a3bca906'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
