"""init

Revision ID: afd4a77b6778
Revises: 7b7db259c400
Create Date: 2023-06-18 02:34:29.265811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afd4a77b6778'
down_revision = '7b7db259c400'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
