"""migrations

Revision ID: b2fbf5af2137
Revises: b62b829b8f0a
Create Date: 2023-06-14 01:12:23.327499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b2fbf5af2137"
down_revision = "b62b829b8f0a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("residence_resident_id_fkey", "residence", type_="foreignkey")
    op.drop_column("residence", "resident_id")
    op.add_column("visit", sa.Column("resident_id", sa.UUID(), nullable=True))
    op.drop_constraint("visit_user_id_fkey", "visit", type_="foreignkey")
    op.create_foreign_key(None, "visit", "resident", ["resident_id"], ["id"])
    op.drop_column("visit", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "visit", sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "visit", type_="foreignkey")
    op.create_foreign_key("visit_user_id_fkey", "visit", "user", ["user_id"], ["id"])
    op.drop_column("visit", "resident_id")
    op.add_column(
        "residence",
        sa.Column("resident_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "residence_resident_id_fkey", "residence", "resident", ["resident_id"], ["id"]
    )
    # ### end Alembic commands ###
