"""migrations

Revision ID: ccc6c9b5996d
Revises: b8cfb3868838
Create Date: 2023-06-14 14:57:21.038801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccc6c9b5996d'
down_revision = 'b8cfb3868838'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
