"""migrations

Revision ID: d9c6c3018d84
Revises: 166a9d327a82
Create Date: 2023-06-14 17:31:46.098239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9c6c3018d84'
down_revision = '166a9d327a82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
