"""migrations

Revision ID: f08e2bfac05a
Revises: d9c6c3018d84
Create Date: 2023-06-14 17:47:51.489339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f08e2bfac05a'
down_revision = 'd9c6c3018d84'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('residence_resident_id_fkey', 'residence', type_='foreignkey')
    op.drop_column('residence', 'resident_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('residence', sa.Column('resident_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('residence_resident_id_fkey', 'residence', 'resident', ['resident_id'], ['id'])
    # ### end Alembic commands ###
