"""migrations

Revision ID: 07764d4c3f15
Revises: b20ff1c09e65
Create Date: 2023-06-24 18:21:11.624029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "07764d4c3f15"
down_revision = "b20ff1c09e65"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
