"""migrations

Revision ID: 1298c4237f78
Revises:
Create Date: 2023-06-24 19:10:41.853519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1298c4237f78"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
