"""migrations

Revision ID: 1a101cc9935c
Revises: b714ad1daa45
Create Date: 2023-06-24 18:32:53.574005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1a101cc9935c"
down_revision = "b714ad1daa45"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
