"""migrations

Revision ID: 261def10978f
Revises: 1298c4237f78
Create Date: 2023-07-16 14:25:22.758499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "261def10978f"
down_revision = "1298c4237f78"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_guard_id_fkey", "user", type_="foreignkey")
    op.drop_constraint("user_resident_id_fkey", "user", type_="foreignkey")
    op.create_foreign_key(None, "user", "resident", ["resident_id"], ["id"])
    op.create_foreign_key(None, "user", "guard", ["guard_id"], ["id"])
    op.add_column("visit", sa.Column("register_date", sa.DateTime(), nullable=True))
    op.drop_constraint("visit_guard_id_fkey", "visit", type_="foreignkey")
    op.drop_constraint("visit_visitor_id_fkey", "visit", type_="foreignkey")
    op.drop_constraint("visit_resident_id_fkey", "visit", type_="foreignkey")
    op.drop_constraint("visit_qr_id_fkey", "visit", type_="foreignkey")
    op.create_foreign_key(None, "visit", "guard", ["guard_id"], ["id"])
    op.create_foreign_key(None, "visit", "visitor", ["visitor_id"], ["id"])
    op.create_foreign_key(None, "visit", "resident", ["resident_id"], ["id"])
    op.create_foreign_key(None, "visit", "qr", ["qr_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "visit", type_="foreignkey")
    op.drop_constraint(None, "visit", type_="foreignkey")
    op.drop_constraint(None, "visit", type_="foreignkey")
    op.drop_constraint(None, "visit", type_="foreignkey")
    op.create_foreign_key(
        "visit_qr_id_fkey", "visit", "qr", ["qr_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        "visit_resident_id_fkey",
        "visit",
        "resident",
        ["resident_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "visit_visitor_id_fkey",
        "visit",
        "visitor",
        ["visitor_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "visit_guard_id_fkey",
        "visit",
        "guard",
        ["guard_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("visit", "register_date")
    op.drop_constraint(None, "user", type_="foreignkey")
    op.drop_constraint(None, "user", type_="foreignkey")
    op.create_foreign_key(
        "user_resident_id_fkey",
        "user",
        "resident",
        ["resident_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "user_guard_id_fkey", "user", "guard", ["guard_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###
