"""migrations

Revision ID: 2c5b148d2f81
Revises: 47934253afe7
Create Date: 2023-06-24 18:40:05.225263

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2c5b148d2f81"
down_revision = "47934253afe7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("resident_residence_id_fkey", "resident", type_="foreignkey")
    op.drop_column("resident", "residence_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "resident",
        sa.Column(
            "residence_id", postgresql.UUID(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        "resident_residence_id_fkey", "resident", "residence", ["residence_id"], ["id"]
    )
    # ### end Alembic commands ###
