"""migrations

Revision ID: 3a0c52b025c4
Revises: d6a66c510bff
Create Date: 2023-06-18 23:53:23.454145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3a0c52b025c4"
down_revision = "d6a66c510bff"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
