"""migrations

Revision ID: 47934253afe7
Revises: a979b1c2b646
Create Date: 2023-06-24 18:38:58.392102

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "47934253afe7"
down_revision = "a979b1c2b646"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "resident",
        sa.Column("residence_id", postgresql.UUID(as_uuid=True), nullable=True),
    )
    op.create_foreign_key(None, "resident", "residence", ["residence_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "resident", type_="foreignkey")
    op.drop_column("resident", "residence_id")
    # ### end Alembic commands ###
