"""migrations

Revision ID: a979b1c2b646
Revises: 1a101cc9935c
Create Date: 2023-06-24 18:34:38.776604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a979b1c2b646"
down_revision = "1a101cc9935c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
