"""migrations

Revision ID: b20ff1c09e65
Revises: f1cddb742174
Create Date: 2023-06-24 18:13:23.468117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b20ff1c09e65"
down_revision = "f1cddb742174"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
