"""migrations

Revision ID: b714ad1daa45
Revises: 07764d4c3f15
Create Date: 2023-06-24 18:28:16.828132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b714ad1daa45"
down_revision = "07764d4c3f15"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
