"""migrations

Revision ID: cb52b9b4ed12
Revises: 68a8fd33c7a4
Create Date: 2023-07-16 13:51:20.698560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cb52b9b4ed12"
down_revision = "68a8fd33c7a4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_resident_id_fkey", "user", type_="foreignkey")
    op.drop_constraint("user_guard_id_fkey", "user", type_="foreignkey")
    op.create_foreign_key(
        None, "user", "resident", ["resident_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "user", "guard", ["guard_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="foreignkey")
    op.drop_constraint(None, "user", type_="foreignkey")
    op.create_foreign_key(
        "user_guard_id_fkey", "user", "guard", ["guard_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        "user_resident_id_fkey",
        "user",
        "resident",
        ["resident_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
