"""migrations

Revision ID: d26f437f2384
Revises:
Create Date: 2023-06-19 04:06:21.004424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d26f437f2384"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
