"""migrations

Revision ID: f1cddb742174
Revises: d26f437f2384
Create Date: 2023-06-19 04:26:59.600031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f1cddb742174"
down_revision = "d26f437f2384"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
